# Generated by Django 2.1 on 2019-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestamujer',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encuestamujer',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mujer',
            name='estadocivil',
            field=models.CharField(choices=[('S', 'SOLTERA'), ('C', 'CONVIVIENTE')], max_length=1),
        ),
    ]
