# Generated by Django 2.1 on 2019-11-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_remove_pregunta_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='likert',
        ),
    ]
