# Generated by Django 2.1 on 2019-11-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_remove_pregunta_likert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='encuesta.Encuesta'),
            preserve_default=False,
        ),
    ]
