# Generated by Django 2.1 on 2019-11-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_pregunta_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaresultado',
            name='pregunta_denom',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
    ]
