# Generated by Django 2.1 on 2019-12-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_pregunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorviolencia',
            name='valord',
        ),
    ]
