# Generated by Django 2.1 on 2019-12-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0009_remove_factorviolencia_valord'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorviolencia',
            name='valord',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
