# Generated by Django 2.1 on 2019-12-31 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_factorviolencia_valord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorviolencia',
            name='encuesta_mujer',
        ),
        migrations.AddField(
            model_name='encuestamujer',
            name='resultado',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Factorviolencia',
        ),
    ]
