# Generated by Django 2.1 on 2019-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_auto_20191230_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestamujer',
            name='resultado',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
